---

- name: Updating Homebrew
  homebrew:
    update_homebrew: true

- name: Upgrading Homebrew Packages
  homebrew:
    upgrade_all: true

- name: Install brew packages
  homebrew:
    name: "{{ item }}"
  loop:
    - bat
    - chezmoi
    - diff-so-fancy
    - glances
    - jq
    - mc
